spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:compass_bank}
    username: ${DB_USER:compass}
    password: ${DB_PASSWORD:compass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: true
    show-sql: false
  main:
    allow-bean-definition-overriding: false
server:
  port: 8080
logging:
  level:
    root: INFO
    com.compassuol.bank: DEBUG
